#!/bin/bash
set -e #exit if any error

dir=/tmp/cartoque-nanoc-output
commit=$(git show|grep commit|awk '{print $2}')
srcbranch=gh-pages-source
currentbranch=$(git branch|grep "*"|awk '{print $2}')

#exit if not on the src branch
[ "$srcbranch" == "$currentbranch" ] || exit 0

#compile the site
rm -rf output/*
nanoc compile >/dev/null

#copy it to a tmp location
rm -rf $dir
cp -a output $dir

#checkout to the gh-pages (final result) branch
git checkout gh-pages 2>/dev/null

#pull the new output content
rsync -az --delete $dir/* . >/dev/null

#commit it
git add .
git commit -a -m "Updated output after commit $commit" >/dev/null && echo "HOOK(post-commit): updated gh-pages branch"

#remove the tmp dir
rm -rf $dir

#back to the normal branch
git checkout $srcbranch 2>/dev/null
